# Site Settings
title: "Stella Spadoni" 
description: "You can reach me at stella.spadoni@imtlucca.it"  
baseurl: ""  # Leave empty for user sites
url: "https://shpadocs.github.io"  # Your GitHub Pages URL
github_username: shpadocs  # Your GitHub username

# Minimal Theme Settings
theme: jekyll-theme-minimal

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

